# Generated by Django 4.1.7 on 2023-04-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default='2000-01-01', max_length=25),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(default=' ', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='Default.jpg', upload_to='profile_pics'),
        ),
    ]
